In [2]:
import torch
import torch.nn as nn
import math
import torch.nn.functional as F

d_model = 512
num_heads = 8
hidden_dim = 256
dropout = 0.2

C:\Users\A\miniconda3\Lib\site-packages\torch\_subclasses\functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [11]:
class Self_Attention_V1(nn.Module):
    def __init__(self, hiddin_dim):
        super().__init__()
        self.hiddin_dim = hiddin_dim
        self.query_proj = nn.Linear(hiddin_dim, hiddin_dim)
        self.key_proj = nn.Linear(hiddin_dim, hiddin_dim)
        self.value_proj = nn.Linear(hiddin_dim, hiddin_dim)



    # X [batch_size,seq,embedding_dim]
    def forward(self, X):
        Q = self.query_proj(X)
        K = self.key_proj(X)
        V = self.value_proj(X)
        attention_weight= F.softmax(Q@K.permute(0,2,1)/math.sqrt(self.hiddin_dim), dim=-1)
        print(attention_weight)
        return (
           attention_weight @V
        )

In [6]:
x1 =torch.randn(3, 3, d_model)
x2 = torch.randn(3, 3, d_model)

In [7]:
x1

tensor([[[ 0.0527, -1.2426,  1.2909,  ..., -1.5253, -0.0935, -1.0982],
         [-0.2250,  1.7235,  0.6064,  ...,  0.3245,  0.7627, -1.2463],
         [ 0.4511,  0.3290, -0.3937,  ...,  0.1170, -1.1236,  0.1804]],

        [[ 1.2248, -0.0044,  0.9529,  ...,  0.7061,  1.3966,  0.1473],
         [ 0.8469, -0.1468,  0.4483,  ..., -0.5446,  0.3984, -1.3787],
         [-2.4589, -0.9692, -1.7227,  ..., -2.1790,  0.5382,  1.3628]],

        [[-0.5517,  0.6642,  0.1396,  ..., -0.4047,  0.2395,  0.8428],
         [ 0.2173, -0.7260, -0.0628,  ...,  0.6815,  1.8872, -0.9055],
         [ 0.6652,  1.4955,  2.5135,  ..., -0.8009,  0.2508,  0.0552]]])

In [8]:
x2

tensor([[[ 0.4359, -1.1808, -0.2646,  ...,  0.7735,  1.1089, -0.3538],
         [-1.7400, -0.7132, -0.0760,  ...,  0.5857,  0.4311, -1.1933],
         [-0.0159, -0.2312,  0.4211,  ...,  0.6084, -1.3262, -1.7870]],

        [[-1.4955,  0.6510,  0.1078,  ...,  0.7017,  0.6321,  1.2937],
         [-1.3954, -0.5071,  0.1763,  ..., -0.7485,  0.3866, -1.6701],
         [-1.1278,  0.9979, -0.3493,  ..., -0.6838, -1.3018,  0.0183]],

        [[ 0.5589, -0.4655,  0.3789,  ..., -0.9265, -0.6771,  1.0752],
         [ 1.7235,  0.9116,  1.3384,  ..., -0.8618, -0.1245,  0.8247],
         [-0.7779, -0.6472, -0.3475,  ..., -0.7419, -0.5665, -0.6998]]])

In [12]:
self_attention_v1 = Self_Attention_V1(d_model)

In [13]:
self_attention_v1(x1)

tensor([[[0.3355, 0.1977, 0.4668],
         [0.2988, 0.5397, 0.1614],
         [0.1966, 0.4930, 0.3104]],

        [[0.4461, 0.3440, 0.2099],
         [0.3270, 0.2781, 0.3948],
         [0.3075, 0.3118, 0.3807]],

        [[0.2655, 0.4441, 0.2904],
         [0.3172, 0.2912, 0.3917],
         [0.1018, 0.4921, 0.4061]]], grad_fn=<SoftmaxBackward0>)


tensor([[[-1.2194e-01, -7.2911e-02,  3.6519e-01,  ..., -4.8389e-01,
           4.6420e-01, -4.0704e-01],
         [-4.7353e-01,  2.2055e-01, -1.3577e-01,  ...,  5.0022e-02,
           2.4765e-02, -5.8594e-02],
         [-3.9524e-01,  1.4390e-01,  1.0377e-04,  ..., -1.0531e-01,
           1.3119e-01, -1.2559e-01]],

        [[ 3.9202e-01, -3.6345e-01, -3.3752e-01,  ...,  1.0022e-01,
          -2.9263e-01, -3.2153e-01],
         [ 2.7521e-01, -2.8127e-01, -2.8557e-01,  ...,  1.6101e-01,
          -2.9369e-03, -3.8306e-01],
         [ 2.7998e-01, -2.9448e-01, -2.5768e-01,  ...,  1.3411e-01,
          -4.0408e-02, -3.6583e-01]],

        [[-8.7865e-02, -2.7265e-01, -8.7093e-01,  ...,  2.6131e-02,
          -2.8588e-02,  4.2560e-01],
         [-6.0543e-02, -3.5559e-01, -7.6949e-01,  ..., -7.2555e-02,
          -1.8804e-01,  4.0430e-01],
         [ 1.0860e-01, -3.3282e-01, -8.0785e-01,  ..., -3.8477e-02,
          -5.7676e-02,  5.8644e-01]]], grad_fn=<UnsafeViewBackward0>)

In [14]:
class Self_Attention_V2(nn.Module):
    def __init__(self, hiddin_dim):
        super().__init__()
        self.hiddin_dim = hiddin_dim
        self.QKV_proj = nn.Linear(hiddin_dim, hiddin_dim*3)
    def forward(self, X):
        QKV = self.QKV_proj(X)
        Q,K,V = torch.split(QKV,hidden_dim,dim=-1)
        attention_weight= F.softmax(Q@K.transpose(-2,-1)/math.sqrt(hidden_dim),dim=-1)
        return attention_weight@V


In [15]:
self_attention_v2= Self_Attention_V2(d_model)


In [16]:
self_attention_v2(x1)

ValueError: too many values to unpack (expected 3)